### ISSUE TITLE
Send error after plugin updateupdate

### ISSUE THREAD

**Issue by igor-panassiouk** [arkhitech/redmine_update_reminder#9]
sudo RAILS_ENV=production rake redmine_update_reminder:send_issue_reminders
rake aborted!
ArgumentError: wrong number of arguments (0 for 1)
/var/lib/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/relation/query_methods.rb:132:in `where'
/var/www/redmine-2.6.6/plugins/redmine_update_reminder/lib/tasks/reminder.rake:92:in `block (2 levels) in send_issue_status_reminders'
/var/www/redmine-2.6.6/plugins/redmine_update_reminder/lib/tasks/reminder.rake:87:in `each'
/var/www/redmine-2.6.6/plugins/redmine_update_reminder/lib/tasks/reminder.rake:87:in `block in send_issue_status_reminders'
/var/www/redmine-2.6.6/plugins/redmine_update_reminder/lib/tasks/reminder.rake:86:in `each'
/var/www/redmine-2.6.6/plugins/redmine_update_reminder/lib/tasks/reminder.rake:86:in `send_issue_status_reminders'
/var/www/redmine-2.6.6/plugins/redmine_update_reminder/lib/tasks/reminder.rake:154:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine_update_reminder:send_issue_reminders

Tried completely remove and install plugin - the same error.

New features to assign different timeouts for different scenarios are very useful and long awaited

**Comment by hishammalik** [comment]
Not able to reproduce. Please make sure you have configured the plugin to provide the group to which reminders are sent and other settings available.

**Comment by igor-panassiouk** [comment]
For all available groups defined numbers for statuses.

How to troubleshoot - which arguments are missing? What row numbers in reminder.rake file mean?

**Comment by igor-panassiouk** [comment]
upgraded to Redmine 3.3.1, plugin works
